{% set name = "neo" %}
{% set version = "0.13.4" %}

package:
  name: python-{{ name }}
  version: {{ version }}

source:
  fn: python-{{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b7264acb7ba7eeaa0a8e91a15ae4dbc8b4dd56c3e38bc7d1cc0442dc5b71dd72

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools  # build backend

  run:
    - python >={{ python_min }}
    # Needed for pkg_resources
    - setuptools
    - packaging
    - numpy >=1.22.4,<2.0.0
    - quantities >=0.16.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - neo
    - neo.core
    - neo.io
    - neo.rawio
    - neo.test
    - neo.test.coretest
    - neo.test.iotest
    - neo.test.rawiotest

about:
  home: http://neuralensemble.org/neo
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A Python package for representing and reading electrophysiology data.
  doc_url: https://neo.readthedocs.io/
  dev_url: https://github.com/NeuralEnsemble/python-neo

extra:
  recipe-maintainers:
    - apdavison
    - jakirkham
    - samuelgarcia
    - zm711
