{% set name = "neo" %}
{% set version = "0.13.1" %}

package:
  name: python-{{ name }}
  version: {{ version }}

source:
  fn: python-{{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 81585b28b65a4dc89a92e71ced3942c5dbfdaa71bdd2cc385371b779b5654cad

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip

  run:
    - python >=3.8
    # Needed for pkg_resources
    - setuptools
    - packaging
    - numpy >=1.19.5
    - quantities >=0.14.1

test:
  imports:
    - neo
    - neo.core
    - neo.io
    - neo.rawio
    - neo.test
    - neo.test.coretest
    - neo.test.iotest
    - neo.test.rawiotest

about:
  home: http://neuralensemble.org/neo
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A Python package for representing and reading electrophysiology data.
  doc_url: https://neo.readthedocs.io/
  dev_url: https://github.com/NeuralEnsemble/python-neo

extra:
  recipe-maintainers:
    - apdavison
    - jakirkham
    - samuelgarcia
    - zm711
