{% set name = "neo" %}
{% set version = "0.7.1" %}

package:
  name: python-{{ name }}
  version: {{ version }}

source:
  fn: python-{{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bae3a2ddbe54362a1fe54613a0f5c24deb2c6372a72a619942035c9227714dc0

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    # Needed for pkg_resources
    - setuptools
    - numpy >=1.7.1
    - quantities >=0.9.0

test:
  imports:
    - neo
    - neo.core
    - neo.io
    - neo.test
    - neo.test.iotest

about:
  home: http://neuralensemble.org/neo
  license: BSD 3-Clause
  # Not yet included in the `sdist`.
  # Raised a PR upstream to include in the future.
  #
  # ref: https://github.com/NeuralEnsemble/python-neo/pull/532
  #
  # license_file: LICENSE.txt
  summary: A Python package for representing and reading electrophysiology data.

extra:
  recipe-maintainers:
    - apdavison
    - jakirkham
    - samuelgarcia
