{% set name = "neo" %}
{% set version = "0.9.0" %}

package:
  name: python-{{ name }}
  version: {{ version }}

source:
  fn: python-{{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6e31c88d7c52174fa2512df589b2b5003e9471fde27fca9f315f4770ba3bd3cb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip

  run:
    - python >=3.6
    # Needed for pkg_resources
    - setuptools
    - numpy >=1.13.0,!=1.16.0
    - quantities >=0.12.1

test:
  imports:
    - neo
    - neo.core
    - neo.io
    - neo.rawio
    - neo.test
    - neo.test.coretest
    - neo.test.iotest
    - neo.test.rawiotest

about:
  home: http://neuralensemble.org/neo
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A Python package for representing and reading electrophysiology data.
  doc_url: https://neo.readthedocs.io/
  dev_url: https://github.com/NeuralEnsemble/python-neo

extra:
  recipe-maintainers:
    - apdavison
    - jakirkham
    - samuelgarcia
