{% set name = "neo" %}
{% set version = "0.8.0" %}

package:
  name: python-{{ name }}
  version: {{ version }}

source:
  fn: python-{{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3382a37b24a384006238b72981f1e9259de9bfa71886f8ed564d35d254ace458

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip

  run:
    - python
    # Needed for pkg_resources
    - setuptools
    - numpy >=1.7.1
    - quantities >=0.9.0

test:
  imports:
    - neo
    - neo.core
    - neo.io
    - neo.test
    - neo.test.iotest

about:
  home: http://neuralensemble.org/neo
  license: BSD 3-Clause
  # Not yet included in the `sdist`.
  # Raised a PR upstream to include in the future.
  #
  # ref: https://github.com/NeuralEnsemble/python-neo/pull/532
  #
  # license_file: LICENSE.txt
  summary: A Python package for representing and reading electrophysiology data.

extra:
  recipe-maintainers:
    - apdavison
    - jakirkham
    - samuelgarcia
