{% set name = "neo" %}
{% set version = "0.14.3" %}

package:
  name: python-{{ name }}
  version: {{ version }}

source:
  fn: python-{{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 50d473fb9070d1728ec6fd72bdad16262b40f7c99df7ff5e8d927ebc2680b080

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools  # build backend

  run:
    - python >={{ python_min }}
    # Needed for pkg_resources
    - setuptools >=78.0.2
    - packaging
    - numpy >=1.24.4
    - quantities >=0.16.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - neo
    - neo.core
    - neo.io
    - neo.rawio
    - neo.test
    - neo.test.coretest
    - neo.test.iotest
    - neo.test.rawiotest

about:
  home: http://neuralensemble.org/neo
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A Python package for representing and reading electrophysiology data.
  doc_url: https://neo.readthedocs.io/
  dev_url: https://github.com/NeuralEnsemble/python-neo

extra:
  recipe-maintainers:
    - apdavison
    - jakirkham
    - samuelgarcia
    - zm711
