travis:
  secure:
    BINSTAR_TOKEN: HaUYR/RUufPpevDZr8tLI8lJa4FRd3QTl0kdxBIWemhbtBvmqgJY5owiuA9pT0SBjvYqupFHnoXaqs5k0oQGCDrwzdhmWkharLzctICRVzEww8lrOvn72F67mXKcRBsGhSOkUn6AfiPKJzDoqF88Qq2c0THEmUCCGeTmCBwn56SdWP59O38rhE/cnRpG48RHFhY2n7zvawcZzOfC2cIIlPktfWIWlXn4OT7LBmBRevVJ4ajn9sXyi3IESpn6MqthVgsYrfE/XrNrrg2/yTosGgFHLdepQSax012npJnkWZewCaauGhpt62eHBdiivGhBDGq0K5kD5BT2oKRJh4xwFm3/609py/Fy13MDpawh3tIPRlclFAJR70latI16IqW8AGCkK2DpS/FtiH5twQeEXa17mjYRysLbwLaxLp2SxE5d8UJ8x5MDyDvc9xhcl95M3Xicc2187BGMkuotRa7BkV8jas09WpRN0JSiMb1JpCwmJsA1i634HqX4oQiUZNFNMGAgVfKumfy8VDnmzr+Ws6oDGVpPcl53F33PPmQvcQ2MgYgImSpU7iAq9FhWnrLqiqd9fSn6S5w33AvV3MCM2p03SVnXroC9K97iLEpkXCRSaeMZ6nmM6gBos0/0VeqWbXYHq1dcRPm4EHaOysGASsYXYLepZRxkB6QvVtc6eb8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
